" General
set nocompatible                     " make VIM incompatible with Vi
autocmd BufWritePre * :%s/\s\+$//e   " strip trailing spaces on save
set encoding=utf8                    " represent text with UTF-8 encoding NOT Latin-1 default
set fileformat=unix                  " line endings are always UNIX
set cursorline                       " highlight current line
set number                           " show line numbers
set ruler                            " show line and column at the bottom right
set showmatch                        " highlight matching brackets
set showmode                         " show current (basic and additional) mode (VISUAL, INSERT, etc.)


" Tabs, spaces, and indentation
set expandtab                        " insert spaces (as per tabstop) when TAB is pressed
set tabstop=4                        " insert 4 spaces for TAB
set shiftwidth=4                     " insert 4 spaces for indentation
set softtabstop=4                    " TAB and DELETE are 4 spaces
set autoindent                       " match indent of previous line
set listchars=space:·,tab:>~ list    " show whitespace characters


" Search
set incsearch                        " search as characters are entered
set ignorecase                       " case-insensitive
set hlsearch                         " highlight matches


" VIM directories
if !isdirectory($HOME . "/.config/vim/tmp")
    call mkdir($HOME . "/.config/vim/tmp/backup", "p", 0700)
    call mkdir($HOME . "/.config/vim/tmp/swap", "p", 0700)
    call mkdir($HOME . "/.config/vim/tmp/undo", "p", 0700)
endif


" VIM files
set viminfo+=n~/.config/vim/viminfo         " VIM info files
set backupdir=~/.config/vim//tmp/backup//   " backup files
set directory=~/.config/vim/tmp/swap//      " swap files
set undodir=~/.config/vim/tmp/undo//        " undo files
" (// creates files using complete file path; preventing name collisions)


" GUI specific
if has("gui_running")
    autocmd GUIEnter * set vb t_vb=  " disable visual bell
    set guicursor+=a:blinkon0        " disable blinking cursor
    colorscheme zellner              " quite pleasant IMO
    " Adjust font and window dimensions per OS
    if has("gui_gtk2") || has("gui_gtk3")
        set guifont=Inconsolata\ 12
        set lines=47
        set columns=70
    elseif has("gui_macvim")
        set guifont=Menlo\ Regular:h14
        set lines=50
        set columns=100
    endif
endif

